### ISSUE TITLE
assignment 3, Problem (B) the M-step

### ISSUE THREAD

**Issue by blossomnoodles** [zyxue/stanford-cs229#19]
#16 
The link you are referring is not correct. Since x^{pr}  is observed and not in the distribution, so you can not drop the first expectation term. You are wokring on the right direction. But your inverse covariance matrix is wrong. The last term of that  matrix should be positive.

**Comment by zyxue** [comment]
Thank you for the comment, but I am a bit confused. 

* Why are you referring to issue 16 (#16)? Don't you mean https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-3/3-EM-application-paper-review-modeling.ipynb. 
* Could you please be more specific on which link is not correct? I will take a closer check.

**Comment by Vrroom** [comment]
Hello I think I found one more problem. As always (lol!) I haven't figured out the solution. 
![screen shot 2018-12-16 at 4 49 26 pm](https://user-images.githubusercontent.com/7254326/50052954-a0e7c280-0152-11e9-85fd-48a7906c6c59.png)
These are the update rules that you have written down. As you can see, that mu_i depend on v_r and v_j depend on mu_p. This means that this rule is incomplete. We'll have to eliminate the dependency by solving for the two equations. I agree that w_i's don't depend on the mu_i and v_j because they are fixed by the previous E step (and by the parameters of the previous iteration) but over here, I think we need to remove the dependency.
As a small example, consider the function z = (xy) + (x^2 * y^2). If we want to find the critical point, by setting partial derivative with respect to x and y respectively to 0, we get (y + 2xy = 0) and (x + 2xy = 0). Now we need to simultaneously solve these two equations instead of doing like what you have done. 
If I have made a mistake in this assessment, please let me know! Cheers!

**Comment by zyxue** [comment]
Thank you, @Vrroom . I really appreciate your input.

No, I meant during the M-step, update mu_i with whatever v_r is from the previous M-step, and then update v_j with whatever mu_p in the same fashion. 

I could be wrong. I think the best way would be to code it up against a real problem, or if you solve the problem, I will check my answer against your answer and see.

**Comment by zyxue** [comment]
Closed for inactivity, feel free to reopen if needed.
